# Generated by Django 5.1.1 on 2024-09-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
